1. first thing--> gensim--> pip install gensim
2. second thing--> model size(1.6gb)
3. pretrain model from the google(google-news)
   
if--
1. pip install gensim  and still facing issue in import
2. this would be because of the mismatch version of the numpy
3. solution:: create new virtual env
4. pip install gensim
5. pip install numpy

In [5]:
from gensim.models import Word2Vec,KeyedVectors
import gensim.downloader as api

In [2]:
model = api.load('word2vec-google-news-300')

In [6]:
model["sunny"]

array([ 1.59179688e-01,  1.07910156e-01,  3.71093750e-02,  1.61132812e-01,
        3.02734375e-01, -3.35937500e-01, -3.83300781e-02, -1.32751465e-03,
       -8.69140625e-02,  2.25585938e-01,  2.23388672e-02,  1.35742188e-01,
       -1.04003906e-01,  1.73828125e-01,  5.46875000e-02,  1.13769531e-01,
       -1.53320312e-01,  2.29492188e-01,  1.13769531e-01,  1.61132812e-02,
       -1.46484375e-01,  5.07812500e-01, -1.08886719e-01, -1.59179688e-01,
       -9.37500000e-02, -6.64062500e-02,  1.90429688e-01,  2.49023438e-01,
       -1.08398438e-01,  2.00195312e-01, -2.19726562e-01,  8.83789062e-02,
        4.98046875e-02,  4.27246094e-02, -3.02734375e-01, -1.64062500e-01,
       -9.86328125e-02, -2.61718750e-01,  1.49414062e-01,  2.12890625e-01,
        2.38281250e-01, -1.50390625e-01,  1.82617188e-01,  1.18408203e-02,
        1.85546875e-02, -1.41601562e-01, -1.41601562e-01,  3.14941406e-02,
       -2.50000000e-01,  2.55859375e-01,  2.53906250e-01,  3.69140625e-01,
        4.43359375e-01,  

In [7]:
len(model["sunny"])

300

In [8]:
model["men"]

array([-4.78515625e-02,  1.66992188e-01,  7.81250000e-02,  2.10571289e-03,
        2.25585938e-01, -2.25585938e-01, -2.09960938e-01, -3.73535156e-02,
       -1.85546875e-02,  1.94335938e-01, -3.00292969e-02, -1.77734375e-01,
        5.20019531e-02,  1.33789062e-01, -1.13769531e-01,  1.10351562e-01,
       -3.27148438e-02,  2.89916992e-03,  9.88769531e-03,  9.27734375e-02,
       -2.19726562e-01, -2.47802734e-02, -8.59375000e-02, -2.67578125e-01,
       -2.51464844e-02, -2.55859375e-01, -1.61132812e-01,  2.53906250e-01,
        5.24902344e-02, -1.00097656e-02,  1.82617188e-01,  7.61718750e-02,
       -1.60980225e-03, -3.10058594e-02, -3.32031250e-02,  1.81640625e-01,
       -3.88183594e-02, -1.83593750e-01, -8.64257812e-02,  2.20703125e-01,
       -7.11059570e-03,  8.60595703e-03,  1.73828125e-01, -9.27734375e-02,
        1.25000000e-01, -1.28906250e-01, -4.85839844e-02, -1.21093750e-01,
        8.00781250e-02,  1.05957031e-01,  1.42578125e-01,  6.78710938e-02,
        6.29882812e-02, -

In [9]:
len(model["men"])

300

In [10]:
model.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [11]:
model.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [12]:
model.most_similar("sunny")

[('balmy', 0.7314587831497192),
 ('sunshine', 0.7251086831092834),
 ('overcast', 0.6918097734451294),
 ('breezy', 0.6885849237442017),
 ('gloriously_sunny', 0.6779158711433411),
 ('sunny_skies', 0.6688455939292908),
 ('chilly', 0.66850346326828),
 ('seasonably_cool', 0.6619703769683838),
 ('windy', 0.6603769659996033),
 ('drizzly', 0.6585174202919006)]

In [13]:
model.similarity('man','woman')

0.76640123

In [14]:
model.similarity('man','python')

0.2097966

In [15]:
model.similarity('man','java')

0.019312028

In [16]:
model.similarity('sunny','Sunny')

0.43010473

In [17]:
model.similarity('python','java')

0.12539075

In [18]:
model.doesnt_match(["PHP","JAVA","DOG","C++"])

'DOG'

In [19]:
vec=model['king'] - model['man'] + model['woman']

In [20]:
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

### Custom Training for Word2Vec(static WordEmbedding)

In [86]:
import pandas as pd
import numpy as np
import os
import gensim
import nltk

In [87]:
nltk.download("all")

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\sunny\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\sunny\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\sunny\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\sunny\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\sunny\AppData\Roaming\nltk_data...
[

True

In [88]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [89]:
story=[]

In [90]:
for file in  os.listdir("./gotbooks"):
  print(file)

001ssb.txt
002ssb.txt
003ssb.txt
004ssb.txt


In [91]:
f=open(r"C:\\Complete_Content\\GENERATIVEAI\\genai_bootcamp\\gotbooks\\001ssb.txt",encoding='unicode_escape')

In [92]:
corpus=f.read()

In [93]:
print(corpus)

A Game Of Thrones 
Book One of A Song of Ice and Fire 
By George R. R. Martin 
PROLOGUE 
"We should start back," Gared urged as the woods began to grow dark around them. "The wildlings are 
dead." 
"Do the dead frighten you?" Ser Waymar Royce asked with just the hint of a smile. 
Gared did not rise to the bait. He was an old man, past fifty, and he had seen the lordlings come and go. 
"Dead is dead," he said. "We have no business with the dead." 
"Are they dead?" Royce asked softly. "What proof have we?" 
"Will saw them," Gared said. "If he says they are dead, that's proof enough for me." 
Will had known they would drag him into the quarrel sooner or later. He wished it had been later rather 
than sooner. "My mother told me that dead men sing no songs," he put in. 
"My wet nurse said the same thing, Will," Royce replied. "Never believe anything you hear at a woman's 
tit. There are things to be learned even from the dead." His voice echoed, too loud in the twilit forest. 
Page 1

"We h

In [94]:
raw_sent=sent_tokenize(corpus)

In [95]:
raw_sent

['A Game Of Thrones \nBook One of A Song of Ice and Fire \nBy George R. R. Martin \nPROLOGUE \n"We should start back," Gared urged as the woods began to grow dark around them.',
 '"The wildlings are \ndead."',
 '"Do the dead frighten you?"',
 'Ser Waymar Royce asked with just the hint of a smile.',
 'Gared did not rise to the bait.',
 'He was an old man, past fifty, and he had seen the lordlings come and go.',
 '"Dead is dead," he said.',
 '"We have no business with the dead."',
 '"Are they dead?"',
 'Royce asked softly.',
 '"What proof have we?"',
 '"Will saw them," Gared said.',
 '"If he says they are dead, that\'s proof enough for me."',
 'Will had known they would drag him into the quarrel sooner or later.',
 'He wished it had been later rather \nthan sooner.',
 '"My mother told me that dead men sing no songs," he put in.',
 '"My wet nurse said the same thing, Will," Royce replied.',
 '"Never believe anything you hear at a woman\'s \ntit.',
 'There are things to be learned even fro

In [96]:
for i in raw_sent:
  print(simple_preprocess(i))

['game', 'of', 'thrones', 'book', 'one', 'of', 'song', 'of', 'ice', 'and', 'fire', 'by', 'george', 'martin', 'prologue', 'we', 'should', 'start', 'back', 'gared', 'urged', 'as', 'the', 'woods', 'began', 'to', 'grow', 'dark', 'around', 'them']
['the', 'wildlings', 'are', 'dead']
['do', 'the', 'dead', 'frighten', 'you']
['ser', 'waymar', 'royce', 'asked', 'with', 'just', 'the', 'hint', 'of', 'smile']
['gared', 'did', 'not', 'rise', 'to', 'the', 'bait']
['he', 'was', 'an', 'old', 'man', 'past', 'fifty', 'and', 'he', 'had', 'seen', 'the', 'lordlings', 'come', 'and', 'go']
['dead', 'is', 'dead', 'he', 'said']
['we', 'have', 'no', 'business', 'with', 'the', 'dead']
['are', 'they', 'dead']
['royce', 'asked', 'softly']
['what', 'proof', 'have', 'we']
['will', 'saw', 'them', 'gared', 'said']
['if', 'he', 'says', 'they', 'are', 'dead', 'that', 'proof', 'enough', 'for', 'me']
['will', 'had', 'known', 'they', 'would', 'drag', 'him', 'into', 'the', 'quarrel', 'sooner', 'or', 'later']
['he', 'wished

In [66]:
folder_path=r"C:\\Complete_Content\\GENERATIVEAI\\genai_bootcamp\\gotbooks"

In [97]:
story=[]
for filename in os.listdir(folder_path):
  file_path=os.path.join(folder_path,filename)
  with open(file_path,encoding='unicode_escape') as f:
    corpus=f.read()
  raw_sent=sent_tokenize(corpus)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [98]:
story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [99]:
story[0]

['game',
 'of',
 'thrones',
 'book',
 'one',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george',
 'martin',
 'prologue',
 'we',
 'should',
 'start',
 'back',
 'gared',
 'urged',
 'as',
 'the',
 'woods',
 'began',
 'to',
 'grow',
 'dark',
 'around',
 'them']

In [100]:
custom_model=gensim.models.Word2Vec(window=10,min_count=5,vector_size=150)

In [101]:
custom_model.build_vocab(story)

In [72]:
custom_model.corpus_count

115483

In [102]:
custom_model.epochs

5

In [103]:
custom_model.corpus_total_words

1312415

In [104]:
custom_model.min_count

5

In [105]:
custom_model.train(story,total_examples=model.corpus_count, epochs=5)

(4898998, 6562075)

In [106]:
custom_model.wv["king"]

array([-0.04816296, -0.00153499, -0.04483328,  0.12899654, -0.05270414,
        0.01079629, -0.03118064,  0.41096556, -0.3027059 , -0.05474425,
        0.1354836 , -0.13066825, -0.36735013,  0.24429138, -0.16172446,
       -0.22485608,  0.2514185 ,  0.09544002,  0.11623639,  0.22116755,
       -0.08999515, -0.03292972,  0.17742565,  0.26661527,  0.11841474,
        0.05422129, -0.35186884, -0.12995155, -0.11986706, -0.26605514,
       -0.01130189, -0.07631791,  0.06673846, -0.21705773, -0.14414454,
        0.14802866,  0.40311223,  0.15228315,  0.26376477, -0.06193671,
       -0.05363673, -0.064684  , -0.3029483 , -0.07770768,  0.10789263,
       -0.06051759, -0.10848546,  0.01909162,  0.20107184,  0.3690908 ,
       -0.20701091,  0.03610309, -0.05729685,  0.08658338,  0.07143634,
       -0.02387383,  0.0586602 , -0.0126181 ,  0.15306856, -0.02208308,
        0.09885913, -0.16842571, -0.03614039, -0.16675547,  0.13353467,
       -0.01472163, -0.08748508, -0.2947393 , -0.37896574, -0.17

In [107]:
custom_model.wv["king"].shape

(150,)

In [110]:
custom_model.wv.most_similar("jon")

[('and', 0.9998698234558105),
 ('the', 0.9998581409454346),
 ('with', 0.9998561143875122),
 ('in', 0.999853789806366),
 ('of', 0.9998535513877869),
 ('had', 0.9998521208763123),
 ('his', 0.9998473525047302),
 ('their', 0.9998375177383423),
 ('was', 0.9998365044593811),
 ('but', 0.9998329281806946)]

In [111]:
custom_model.wv.most_similar("arya")

[('had', 0.9988039135932922),
 ('black', 0.998798131942749),
 ('was', 0.9987817406654358),
 ('of', 0.9987631440162659),
 ('eyes', 0.9987547993659973),
 ('with', 0.9987547397613525),
 ('in', 0.9987401962280273),
 ('the', 0.9987377524375916),
 ('and', 0.998734712600708),
 ('he', 0.998718798160553)]

In [112]:
custom_model.wv.most_similar("tyrion")

[('his', 0.9993563294410706),
 ('but', 0.9993320107460022),
 ('and', 0.9993317723274231),
 ('as', 0.9993277192115784),
 ('the', 0.9993201494216919),
 ('so', 0.9993128180503845),
 ('that', 0.9993128180503845),
 ('in', 0.9993114471435547),
 ('of', 0.9993003010749817),
 ('to', 0.9993000030517578)]

In [113]:
custom_model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'sansa'

In [114]:
custom_model.wv.doesnt_match(['cersei', 'jaime', 'bronn', 'tyrion'])

'bronn'

Assisgnment

1.  you have to take one dataset from kaggle from any where(web)
2.  train you custom word2vec model
3.  then suppers dimesion of vectors into 2 dimesion using PCA(dimesion reduction)
4.  then plot the data using graph(plot 2-d data)
5.  check the similarity between the words
6.  then send it to me inside th chat section keep your soltion over the github or drive and send the link in the community chat