In [1]:
print("all ok")

all ok


In [2]:
import torch

In [8]:
torch.__version__

'2.5.1+cpu'

In [11]:
!pip install nvidia-smi

In [13]:
if torch.cuda.is_available():
    print("cuda is available")
else:
    print("cuda is not available")

cuda is not available


In [17]:
torch.empty(2,3) # Creating empty array with garbage values

tensor([[-4.5060e+15,  1.7965e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [18]:
a = torch.empty(2,3)
type(a) # Tensor - A form of array 

torch.Tensor

In [20]:
a.fill_(0) # Filling tensor array with zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
torch.zeros(2,4) # zeros metrics

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
torch.ones(2,4) # ones metrics

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
torch.rand(3,4) # 3x4 matrix with random values

tensor([[0.7073, 0.8131, 0.2542, 0.0871],
        [0.6212, 0.6777, 0.7251, 0.8026],
        [0.4524, 0.4792, 0.5815, 0.8434]])

In [28]:
torch.rand(3,4) # 3x4 matrix with random values

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [29]:
torch.manual_seed(42) # Setting seed value for reproducibility
torch.rand(3,4) # 3x4 matrix with random values

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [30]:
torch.manual_seed(42) # Setting seed value for reproducibility
torch.rand(3,4) # 3x4 matrix with random values

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [32]:
torch.tensor([[1,2,3], [4,5,6]]) # Creating tensor from list

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
torch.arange(10) # range functionality

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
torch.arange(3, 10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [36]:
torch.arange(3, 10, 2)

tensor([3, 5, 7, 9])

In [38]:
torch.linspace(0,10,20) # to generate 20 numbers between 0 and 10

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [39]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [41]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [44]:
x = torch.tensor([[1,2,3], [4,5,6]]) # Creating tensor from list
x.shape

torch.Size([2, 3])

In [49]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [50]:
torch.zeros_like(x) # zeros metrics 

tensor([[0, 0, 0],
        [0, 0, 0]])

In [51]:
torch.rand_like(x, dtype=torch.float32) # zeros metrics random matrix

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


| **DataType**    | **Dtype**           | **Description**                                                                 |
|------------------|---------------------|---------------------------------------------------------------------------------|
| 32-bit floating point | `torch.float32`   | Standard single-precision float; default floating-point type in PyTorch.       |
| 64-bit floating point | `torch.float64`   | Double-precision floating-point, used for higher precision computations.       |
| 16-bit floating point | `torch.float16`   | Half-precision float; often used for mixed precision training to save memory.  |
| 8-bit floating point  | `torch.bfloat16`  | Brain floating-point; efficient for large-scale training with lower precision. |
| 8-bit integer (signed) | `torch.int8`      | Signed 8-bit integer, typically used for quantized models.                     |
| 8-bit integer (unsigned) | `torch.uint8`  | Unsigned 8-bit integer, often used for image processing (e.g., RGB values).    |
| 16-bit integer (signed) | `torch.int16`   | Signed 16-bit integer for medium-range integer values.                         |
| 32-bit integer (signed) | `torch.int32`   | Standard signed 32-bit integer type.                                           |
| 64-bit integer (signed) | `torch.int64`   | Standard signed 64-bit integer type; commonly used for indexing.               |
| Boolean         | `torch.bool`        | Boolean type, used for storing `True`/`False` values.                          |
| Complex64       | `torch.complex64`   | Complex number with two 32-bit floats for real and imaginary parts.            |
| Complex128      | `torch.complex128`  | Complex number with two 64-bit floats for real and imaginary parts.            |
| Quantized int8  | `torch.qint8`       | Quantized 8-bit signed integer type.                                           |
| Quantized uint8 | `torch.quint8`      | Quantized 8-bit unsigned integer type.                                         |
| Quantized int32 | `torch.qint32`      | Quantized 32-bit signed integer type.                                          |



In [63]:
c = torch.tensor([1,-2,-3, 4]) 
print(c)

torch.abs(c) # absolute values : negative value -> positive value

tensor([ 1, -2, -3,  4])


tensor([1, 2, 3, 4])

In [64]:
torch.neg(c) # negative of tensor : negative -> positive, positive -> negative

tensor([-1,  2,  3, -4])

In [70]:
d = torch.tensor([1.9,2.3,3.5,4.8])
print(torch.round(d))# round off the values
print(torch.floor(d))# round off the values to lower bound
print(torch.ceil(d)) # round off the values to upper bound

tensor([2., 2., 4., 5.])
tensor([1., 2., 3., 4.])
tensor([2., 3., 4., 5.])


In [72]:
e = torch.randint(size=(3,4), low=0, high=10) # random integer values between 0 and 10
print(e)

tensor([[2, 0, 5, 9],
        [3, 4, 9, 6],
        [2, 0, 6, 2]])


In [73]:
torch.sum(e) # sum of all elements

tensor(48)

In [75]:
torch.sum(e, dim=0) # column wise sum

tensor([ 7,  4, 20, 17])

In [76]:
torch.sum(e, dim=1) # row wise sum

tensor([16, 22, 10])

In [77]:
torch.mean(e) # mean of all elements

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [78]:
torch.min(e)

tensor(0)

In [79]:
torch.max(e)

tensor(9)

In [80]:
torch.argmax(e) # index of maximum value

tensor(3)

In [81]:
torch.argmin(e) # index of maximum value

tensor(1)

In [82]:
e

tensor([[2, 0, 5, 9],
        [3, 4, 9, 6],
        [2, 0, 6, 2]])

In [87]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([4,5])
print(vector1)
print(vector2)

tensor([1, 2])
tensor([4, 5])


In [88]:
vector1 * vector2  # 1 * 4 , 2 * 5

tensor([ 4, 10])

In [89]:
torch.dot(vector1, vector2) # Dot product -> 1*4 + 2*5 = 14

tensor(14)

In [90]:
torch.transpose(e, 0, 1) # Transpose of matrix

tensor([[2, 3, 2],
        [0, 4, 0],
        [5, 9, 6],
        [9, 6, 2]])