# Breast Cancel Detection

In [37]:
import pandas as pd 

# Raw URL of the CSV file
url = "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv"

# Read the CSV into a DataFrame
df = pd.read_csv(url)
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [38]:
df.shape

(569, 33)

In [39]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [40]:
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [41]:
df.drop(columns=['id', 'Unnamed: 32'], axis=1, inplace=True)

In [42]:
df.shape

(569, 31)

In [43]:
df['diagnosis'].value_counts() # B - No cancel , M - Cancer

diagnosis
B    357
M    212
Name: count, dtype: int64

In [44]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection  import train_test_split

In [45]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [46]:
X_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
257       15.320         17.27          103.20      713.3          0.13350   
154       13.150         15.34           85.31      538.9          0.09384   
390       10.260         12.22           65.75      321.6          0.09996   
416        9.405         21.70           59.60      271.2          0.10440   
101        6.981         13.43           43.79      143.5          0.11700   
..           ...           ...             ...        ...              ...   
370       16.350         23.29          109.00      840.4          0.09742   
1         20.570         17.77          132.90     1326.0          0.08474   
163       12.340         22.22           79.85      464.5          0.10120   
464       13.170         18.22           84.28      537.3          0.07466   
52        11.940         18.24           75.71      437.6          0.08261   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
257           0.22840         0.24480              0.12420         0.2398   
154           0.08498         0.09293              0.03483         0.1822   
390           0.07542         0.01923              0.01968         0.1800   
416           0.06159         0.02047              0.01257         0.2025   
101           0.07568         0.00000              0.00000         0.1930   
..                ...             ...                  ...            ...   
370           0.14970         0.18110              0.08773         0.2175   
1             0.07864         0.08690              0.07017         0.1812   
163           0.10150         0.05370              0.02822         0.1551   
464           0.05994         0.04859              0.02870         0.1454   
52            0.04751         0.01972              0.01349         0.1868   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
257                 0.07596  ...         17.73          22.66   
154                 0.06207  ...         14.77          20.50   
390                 0.06569  ...         11.38          15.65   
416                 0.06601  ...         10.85          31.24   
101                 0.07818  ...          7.93          19.54   
..                      ...  ...           ...            ...   
370                 0.06218  ...         19.38          31.03   
1                   0.05667  ...         24.99          23.41   
163                 0.06761  ...         13.58          28.68   
464                 0.05549  ...         14.90          23.89   
52                  0.06110  ...         13.10          21.33   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
257           119.80       928.8            0.1765            0.45030   
154            97.67       677.3            0.1478            0.22560   
390            73.23       394.5            0.1343            0.16500   
416            68.73       359.4            0.1526            0.11930   
101            50.41       185.2            0.1584            0.12020   
..               ...         ...               ...                ...   
370           129.30      1165.0            0.1415            0.46650   
1             158.80      1956.0            0.1238            0.18660   
163            87.36       553.0            0.1452            0.23380   
464            95.10       687.6            0.1282            0.19650   
52             83.67       527.2            0.1144            0.08906   

     concavity_worst  concave points_worst  symmetry_worst  \
257          0.44290               0.22290          0.3258   
154          0.30090               0.09722          0.3849   
390          0.08615               0.06696          0.2937   
416          0.06141               0.03770          0.2872   
101          0.00000               0.00000          0.2932   
..               ...                   ...             ...   
370          0.70870               0.22480         

In [47]:
X_test

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
486       14.640         16.85           94.21      666.0          0.08641   
269       10.710         20.39           69.50      344.9          0.10820   
316       12.180         14.08           77.25      461.4          0.07734   
372       21.370         15.10          141.30     1386.0          0.10010   
180       27.220         21.87          182.10     2250.0          0.10940   
..           ...           ...             ...        ...              ...   
492       18.010         20.56          118.40     1007.0          0.10010   
422       11.610         16.02           75.46      408.2          0.10880   
66         9.465         21.01           60.11      269.4          0.10440   
20        13.080         15.71           85.63      520.0          0.10750   
226       10.440         15.46           66.62      329.6          0.10530   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
486           0.06698        0.051920             0.027910         0.1409   
269           0.12890        0.084480             0.028670         0.1668   
316           0.03212        0.011230             0.005051         0.1673   
372           0.15150        0.193200             0.125500         0.1973   
180           0.19140        0.287100             0.187800         0.1800   
..                ...             ...                  ...            ...   
492           0.12890        0.117000             0.077620         0.2116   
422           0.11680        0.070970             0.044970         0.1886   
66            0.07773        0.021720             0.015040         0.1717   
20            0.12700        0.045680             0.031100         0.1967   
226           0.07722        0.006643             0.012160         0.1788   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
486                 0.05355  ...         16.46          25.44   
269                 0.06862  ...         11.69          25.21   
316                 0.05649  ...         12.85          16.47   
372                 0.06183  ...         22.69          21.84   
180                 0.05770  ...         33.12          32.85   
..                      ...  ...           ...            ...   
492                 0.06077  ...         21.53          26.06   
422                 0.06320  ...         12.64          19.67   
66                  0.06899  ...         10.41          31.56   
20                  0.06811  ...         14.50          20.49   
226                 0.06450  ...         11.52          19.80   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
486           106.00       831.0            0.1142            0.20700   
269            76.51       410.4            0.1335            0.25500   
316            81.60       513.1            0.1001            0.05332   
372           152.10      1535.0            0.1192            0.28400   
180           220.80      3216.0            0.1472            0.40340   
..               ...         ...               ...                ...   
492           143.40      1426.0            0.1309            0.23270   
422            81.93       475.7            0.1415            0.21700   
66             67.03       330.7            0.1548            0.16640   
20             96.09       630.5            0.1312            0.27760   
226            73.47       395.4            0.1341            0.11530   

     concavity_worst  concave points_worst  symmetry_worst  \
486          0.24370               0.07828          0.2455   
269          0.25340               0.08600          0.2605   
316          0.04116               0.01852          0.2293   
372          0.40240               0.19660          0.2730   
180          0.53400               0.26880          0.2856   
..               ...                   ...             ...   
492          0.25440               0.14890         

In [48]:
y_test

486    B
269    B
316    B
372    M
180    M
      ..
492    M
422    B
66     B
20     B
226    B
Name: diagnosis, Length: 114, dtype: object

In [49]:
y_train

257    M
154    B
390    B
416    B
101    B
      ..
370    M
1      M
163    B
464    B
52     B
Name: diagnosis, Length: 455, dtype: object

In [50]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [51]:
X_train_scaled

array([[ 0.31119971, -0.48014723,  0.44245118, ...,  1.65552669,
         0.59144541,  1.97062963],
       [-0.31892574, -0.92094562, -0.31275131, ..., -0.25574671,
         1.54514423,  0.16156141],
       [-1.15812508, -1.63353162, -1.13845063, ..., -0.7159244 ,
         0.07344657, -0.34135625],
       ...,
       [-0.55413386,  0.65039786, -0.54323793, ..., -0.48811667,
        -1.00612113,  0.40943191],
       [-0.31311814, -0.26317393, -0.35623139, ..., -0.14503641,
        -1.05937335, -0.78134019],
       [-0.67028602, -0.25860607, -0.71800251, ..., -0.77675424,
        -0.17183638, -0.51469998]], shape=(455, 30))

In [52]:
X_test_scaled

array([[ 0.11374104, -0.57607227,  0.06295032, ..., -0.54377597,
        -0.70435856, -0.96296467],
       [-1.0274539 ,  0.23243877, -0.98014938, ..., -0.42637439,
        -0.46230302,  0.19910082],
       [-0.60059473, -1.20872073, -0.65299347, ..., -1.4525737 ,
        -0.96577854, -1.27156069],
       ...,
       [-1.38897749,  0.37404239, -1.37653571, ..., -0.74314575,
        -0.02176195,  0.48064638],
       [-0.33925237, -0.83644023, -0.29924294, ..., -0.62665662,
         0.47203135, -0.08686114],
       [-1.10585661, -0.89353847, -1.10172474, ..., -1.05535488,
        -0.44616599, -0.03938483]], shape=(114, 30))

In [53]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.fit_transform(y_test)

In [54]:
y_train_encoded

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [55]:
y_test_encoded

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0])

In [56]:
import torch
X_train_tensor = torch.from_numpy(X_train_scaled.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test_scaled.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train_encoded.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test_encoded.astype(np.float32))

In [57]:
X_train_tensor.dtype

torch.float32

In [58]:
type(X_train_tensor)


torch.Tensor

In [59]:
X_train_tensor

tensor([[ 0.3112, -0.4801,  0.4425,  ...,  1.6555,  0.5914,  1.9706],
        [-0.3189, -0.9209, -0.3128,  ..., -0.2557,  1.5451,  0.1616],
        [-1.1581, -1.6335, -1.1385,  ..., -0.7159,  0.0734, -0.3414],
        ...,
        [-0.5541,  0.6504, -0.5432,  ..., -0.4881, -1.0061,  0.4094],
        [-0.3131, -0.2632, -0.3562,  ..., -0.1450, -1.0594, -0.7813],
        [-0.6703, -0.2586, -0.7180,  ..., -0.7768, -0.1718, -0.5147]])

In [60]:
X_test_tensor

tensor([[ 0.1137, -0.5761,  0.0630,  ..., -0.5438, -0.7044, -0.9630],
        [-1.0275,  0.2324, -0.9801,  ..., -0.4264, -0.4623,  0.1991],
        [-0.6006, -1.2087, -0.6530,  ..., -1.4526, -0.9658, -1.2716],
        ...,
        [-1.3890,  0.3740, -1.3765,  ..., -0.7431, -0.0218,  0.4806],
        [-0.3393, -0.8364, -0.2992,  ..., -0.6267,  0.4720, -0.0869],
        [-1.1059, -0.8935, -1.1017,  ..., -1.0554, -0.4462, -0.0394]])

In [61]:
y_train_tensor

tensor([1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
        0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1.,
        0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
        0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1.,
        1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1.,
        0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 

In [62]:
y_test_tensor

tensor([0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
        1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0.,
        0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
        1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0.,
        1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1.,
        0., 1., 0., 0., 0., 0.])

In [63]:
df.shape

(569, 31)

In [64]:
X_train_tensor.shape

torch.Size([455, 30])

In [65]:
learning_rate = 0.1 ## Hyperparameter
epochs = 20 ## One forward + One Backward = 1 Epoch

In [66]:
## Loss function 
import torch.nn as nn 
loss_funtion = nn.BCELoss() # Binary Cross Entropy

In [67]:
class SimpleNeuralNetwork(nn.Module):
    def __init__(self, new_feature):
        super().__init__()
        self.linear1 = nn.Linear(new_feature, 3) # Hidden layer with 3 neuron
        self.relu = nn.ReLU() ## To apply Relu on Hidden layer
        self.linear2 = nn.Linear(3, 1) # Ouput layer
        self.sigmoid = nn.Sigmoid() # To apply Sigmoid on output layer

    def forward(self, features):
        output = self.linear1(features)
        output = self.relu(output)
        output = self.linear2(output)
        output = self.sigmoid(output)
        return output

In [68]:
model = SimpleNeuralNetwork(30)
model

SimpleNeuralNetwork(
  (linear1): Linear(in_features=30, out_features=3, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [69]:
## Optimizer 
optimizer = torch.optim.SGD(model.parameters(), lr= learning_rate)

In [70]:
y_train_tensor.view(-1,1)

tensor([[1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
      

In [71]:
for epoch in range(epochs):
    ## Forward pass 
    y_pred = model(X_train_tensor)

    ## loss calculation
    loss = loss_funtion(y_pred, y_train_tensor.view(-1,1)) ## view -> to convert into 1D array

    ## To calculate Gradient -> Optimizer
    optimizer.zero_grad()

    ## Backward Propogation
    loss.backward()

    ## Paramater updation
    optimizer.step()

    ## Printing Epoch and loss
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.6760492920875549
Epoch: 2, Loss: 0.6620670557022095
Epoch: 3, Loss: 0.6482400298118591
Epoch: 4, Loss: 0.6343316435813904
Epoch: 5, Loss: 0.6202483177185059
Epoch: 6, Loss: 0.6059899926185608
Epoch: 7, Loss: 0.5916560888290405
Epoch: 8, Loss: 0.57710200548172
Epoch: 9, Loss: 0.5620502829551697
Epoch: 10, Loss: 0.5463389158248901
Epoch: 11, Loss: 0.5304031372070312
Epoch: 12, Loss: 0.5140149593353271
Epoch: 13, Loss: 0.4974101781845093
Epoch: 14, Loss: 0.48077577352523804
Epoch: 15, Loss: 0.46414467692375183
Epoch: 16, Loss: 0.4475858211517334
Epoch: 17, Loss: 0.43127933144569397
Epoch: 18, Loss: 0.4152878522872925
Epoch: 19, Loss: 0.3996724486351013
Epoch: 20, Loss: 0.3845237195491791


In [72]:
## Calculating Accuracy
with torch.no_grad(): # no_grad -> No need to calculate the Gradient
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"accuracy : {accuracy.item()}")

accuracy : 0.5492458939552307
